frontend/vizzy/app/auth/signup/components/user-signup-form.tsx
frontend/vizzy/app/auth/signup/page.tsx
frontend/vizzy/app/auth/signup/schema/user-signup-form-schema.ts
frontend/vizzy/app/auth/signup/utils/signup-user.ts

Updated file and function names to be less generic.

Update File & Function Names

---

Frontend/vizzy/app/auth/reset-password/components/reset-password-form.tsx
Frontend/vizzy/app/auth/reset-password/page.tsx
Frontend/vizzy/app/auth/reset-password/schema/resetPasswordSchema.ts
Frontend/vizzy/app/auth/reset-password/utils/sendResetEmail.ts

Front-end of the reset-password page.

reset-password page

---

frontend/vizzy/app/auth/login/page.tsx

Correção de erros no redirecionamento dos botões

Correção de erros

---

backend/Vizzy.Api/.dockerignore
backend/Vizzy.Api/Controllers/UserController.cs
backend/Vizzy.Api/Dockerfile

Add Dockerfile for containerizing C# API

Add Dockerfile for containerizing API

---

backend/Vizzy.Api/Program.cs
backend/Vizzy.Api/Vizzy.Api.csproj
backend/Vizzy.Api/appsettings.json
frontend/vizzy/app/page.tsx

Added JWT authentication and authorization to the C# Backend API.

Add JWT Auth

---

frontend/vizzy/app/page.tsx
frontend/vizzy/components/i18n/language-switcher.tsx
frontend/vizzy/i18n/config.ts
frontend/vizzy/i18n/request.ts
frontend/vizzy/services/locale.ts

Implemented component to change the language by setting a cookie. Automatically get this cookie to load the current language.

Button to Change Language

---

frontend/vizzy/components/layout/user-menu.tsx
frontend/vizzy/components/theme/theme-toggle.tsx
frontend/vizzy/messages/en.json
frontend/vizzy/messages/pt.json

Added translations for the nav bar components in EU and PT.

Add Nav Translations

---

frontend/vizzy/app/page.tsx
frontend/vizzy/app/profile/[username]/components/user-listings.tsx
frontend/vizzy/app/profile/[username]/layout.tsx
frontend/vizzy/app/profile/[username]/page.tsx
frontend/vizzy/components/layout/footer.tsx
frontend/vizzy/components/ui/badge.tsx
frontend/vizzy/components/ui/listing-card.tsx
frontend/vizzy/messages/en.json
frontend/vizzy/messages/pt.json
frontend/vizzy/next.config.ts
frontend/vizzy/types/listing.ts

Created the dynamic profile page with mock data.

Create profile page

---

frontend/vizzy/app/page.tsx
frontend/vizzy/app/profile/[username]/layout.tsx
frontend/vizzy/components/layout/nav-bar.tsx
frontend/vizzy/components/layout/user-menu.tsx
frontend/vizzy/messages/en.json
frontend/vizzy/messages/pt.json
frontend/vizzy/package-lock.json
frontend/vizzy/package.json
frontend/vizzy/types/jwt-payload.ts
frontend/vizzy/types/profile-metadata.ts
frontend/vizzy/utils/cookies/get-client-cookie.ts
frontend/vizzy/utils/cookies/get-server-cookie.ts
frontend/vizzy/utils/token/decode-token.ts
frontend/vizzy/utils/token/get-client-user-id.ts
frontend/vizzy/utils/token/get-client-user.ts
frontend/vizzy/utils/token/get-server-user-id.ts
frontend/vizzy/utils/token/get-server-user.ts

Added functions to fetch user session data by decoding the JWT cookie.
Updated the nav bar to use this metadata.

Add Functions to Get User Session Data

---

frontend/vizzy/app/account-settings/account/components/delete-account-button.tsx
frontend/vizzy/app/account-settings/account/page.tsx
frontend/vizzy/app/auth/change-password/components/user-auth-form.tsx
frontend/vizzy/app/auth/login/components/user-login-form.tsx
frontend/vizzy/app/auth/login/page.tsx
frontend/vizzy/app/auth/reset-password/page.tsx
frontend/vizzy/app/auth/signup/components/user-signup-form.tsx
frontend/vizzy/app/auth/signup/page.tsx
frontend/vizzy/app/profile/page.tsx
frontend/vizzy/constants/links.ts
frontend/vizzy/constants/routes.ts

Updated frontend to use route constants instead of hardcoded strings.

Use Constants for Routing

---

backend/vizzy-backend/src/auth/auth.controller.ts
backend/vizzy-backend/src/auth/auth.service.ts
backend/vizzy-backend/src/auth/helpers/cookie.helper.ts
frontend/vizzy/lib/auth/refresh-session.ts
frontend/vizzy/middleware.ts

Implementation of automatic refresh token in backend

Refresh token

---

backend/vizzy-backend/src/proposal/proposal.controller.ts
frontend/vizzy/app/dashboard/layout/proposals-page.tsx
frontend/vizzy/components/proposals/swap-proposal-dialog.tsx
frontend/vizzy/components/ui/common/block-button.tsx
frontend/vizzy/components/ui/overlay/alert-dialog.tsx
frontend/vizzy/lib/api/proposals/create-proposal.ts
frontend/vizzy/lib/api/proposals/upload-proposal-images.ts

KNOWN ERROR: Known error with the create proposal endpoint, returns all values undefined so the call to create images will not work.

feat: upload-images

---

.github/workflows/danger-js-pr-review.yml
.gitignore
dangerfile.ts
package-lock.json
package.json

Adds Danger JS to automatically review and look over common PR issues.

chore: add danger js pr review automation

---

backend/vizzy-backend/package-lock.json
backend/vizzy-backend/package.json
backend/vizzy-backend/src/app.module.ts
backend/vizzy-backend/src/common/guards/throttler.guard.ts
backend/vizzy-backend/src/main.ts

Added a global api rate limit of 10 requests per minute.

chore: add global api rate limit

---

frontend/vizzy/app/auth/forgot-password/components/forgot-password-form.tsx
frontend/vizzy/app/auth/login/components/user-login-form.tsx
frontend/vizzy/app/auth/reset-password/components/user-auth-form.tsx
frontend/vizzy/app/auth/signup/components/steps/account-setup-step.tsx
frontend/vizzy/app/auth/signup/components/steps/basic-info-step.tsx
frontend/vizzy/app/auth/signup/components/steps/location-step.tsx

Added ctrl-enter shortcut to submit auth forms for better UX.

feat: ctrl-enter shortcut to submit auth forms

---

backend/vizzy-backend/src/proposal/helpers/proposal-database.helper.ts
backend/vizzy-backend/src/proposal/proposal.controller.ts
backend/vizzy-backend/src/proposal/proposal.service.ts
frontend/vizzy/app/dashboard/layout/overview-page.tsx
frontend/vizzy/lib/api/proposals/fetch-user-balance.ts

Made the feat to put the user balance in the dashboard

feat: dashboard total value

---

frontend/vizzy/app/dashboard/layout/listings-page.tsx
frontend/vizzy/components/listings/listing-card-normal.tsx
frontend/vizzy/components/listings/listing-card-small.tsx
frontend/vizzy/components/listings/listing-card.tsx
frontend/vizzy/components/proposals/proposal-card.tsx

Refactored the listing card to accept optional parameter for card size and created variants of this card - normal and small.

refactor: create small variant of listing card

---

backend/vizzy-backend/src/listing/helpers/listing-database.helper.ts
frontend/vizzy/app/listing/[id]/page.tsx
frontend/vizzy/components/proposals/purchase-proposal-dialog.tsx
frontend/vizzy/components/proposals/rental-proposal-dialog.tsx
frontend/vizzy/components/proposals/swap-proposal-dialog.tsx
frontend/vizzy/lib/api/listings/fetch-listing-images.ts

Unauthorized users can see the listings' images and the carousel works correctly.

fix: listing images

---

backend/vizzy-backend/src/user/helpers/user-database.helper.ts
frontend/vizzy/components/profiles/profile-hover-card.tsx
frontend/vizzy/components/ui/data-display/hover-card.tsx
frontend/vizzy/package-lock.json
frontend/vizzy/package.json

Update dos dados de utilizador e componente hover card..

fix: user data

---

backend/vizzy-backend/src/dtos/proposal/proposal-response.dto.ts
backend/vizzy-backend/src/proposal/helpers/proposal-database.helper.ts
frontend/vizzy/app/dashboard/dashboard-page-client.tsx
frontend/vizzy/app/dashboard/layout/overview-page.tsx
frontend/vizzy/app/dashboard/layout/proposals-page.tsx
frontend/vizzy/app/dashboard/proposals/[id]/proposal-details/page.tsx
frontend/vizzy/components/proposals/proposal-card.tsx
frontend/vizzy/lib/api/proposals/fetch-user-balance.ts
frontend/vizzy/lib/api/proposals/fetch-user-proposals.ts
frontend/vizzy/lib/api/proposals/update-proposal-status.ts
frontend/vizzy/types/balance.ts
frontend/vizzy/types/proposal.ts

Proposal details page was not fetching data correctly Overview page not receiving the balance.

fix: dashboard pages

---

frontend/vizzy/app/dashboard/layout/listings-page.tsx
frontend/vizzy/app/dashboard/layout/proposals-page.tsx
frontend/vizzy/app/dashboard/proposals/[id]/proposal-details/page.tsx
frontend/vizzy/hooks/use-listings.ts
frontend/vizzy/lib/api/listings/fetch-user-listings.ts
frontend/vizzy/lib/api/proposals/fetch-user-proposals.ts
frontend/vizzy/lib/api/proposals/update-proposal-status.ts
frontend/vizzy/lib/utils/token/get-server-user-action.ts

Api calls to match the new criteria

fix: frontend api calls

---

frontend/vizzy/app/dashboard/proposals/[id]/proposal-details/page.tsx

fix:api calls 3

---

frontend/vizzy/app/profile/[username]/components/user-listings.tsx
frontend/vizzy/app/settings/hooks/useContacts.ts
frontend/vizzy/app/settings/hooks/useProfileData.ts
frontend/vizzy/components/listings/create-listing-dialog.tsx
frontend/vizzy/components/proposals/swap-proposal-dialog.tsx
frontend/vizzy/lib/actions/auth/get-user-metadata-action.ts
frontend/vizzy/lib/services/auth/signup-service.ts

Fixed production errors such as contacts hook & signup TS warnings.

fix: prod errors

---

backend/vizzy-backend/src/dtos/profile/update-profile.dto.ts
backend/vizzy-backend/src/profile/tests/integration/profile.database-helper.integration-spec.ts
backend/vizzy-backend/src/profile/tests/unit/profile.controller.spec.ts
backend/vizzy-backend/src/profile/tests/unit/profile.service.spec.ts

Implementation of integration tests for profile

test: profile integration tests

---

backend/vizzy-backend/src/dtos/listing/create-listing.dto.ts
backend/vizzy-backend/src/dtos/listing/sale-listing.dto.ts
backend/vizzy-backend/src/listing/tests/integration/listing.database-helper.integration-spec.ts
backend/vizzy-backend/src/listing/tests/unit/listing.controller.spec.ts
backend/vizzy-backend/src/listing/tests/unit/listing.service.spec.ts
backend/vizzy-backend/supabase/seeds/listing_statuses.sql
backend/vizzy-backend/supabase/seeds/listing_types.sql

Implementation of integration tests for listings

test: listing integration tests

---

backend/vizzy-backend/src/proposal/tests/integration/proposal.database-helper.integration-spec.ts
backend/vizzy-backend/src/proposal/tests/unit/proposal.controller.spec.ts
backend/vizzy-backend/src/proposal/tests/unit/proposal.service.spec.ts

Implementation of integration tests for the proposals

test: integration tests

---

frontend/vizzy/app/dashboard/dashboard-page-client.tsx
frontend/vizzy/app/dashboard/layout/proposals-page.tsx
frontend/vizzy/app/dashboard/proposals/[id]/proposal-details/page.tsx
frontend/vizzy/components/proposals/cancel-proposal-dialog.tsx
frontend/vizzy/components/proposals/proposal-card.tsx
frontend/vizzy/components/ui/common/badge.tsx
frontend/vizzy/lib/api/proposals/fetch-user-proposals.ts

fix on filter of cancelled proposals

fix: cancelled filter in dashboard

---

backend/vizzy-backend/src/listing/listing.service.ts
backend/vizzy-backend/src/listing/tests/unit/listing.service.spec.ts

Implemented a function to invalidate user listings cache when a new listing is created

feat: invalidate user listings cache

---

frontend/vizzy/app/dashboard/proposals/[id]/proposal-details/page.tsx
frontend/vizzy/app/listing/[id]/page.tsx
frontend/vizzy/components/proposals/proposal-card.tsx
frontend/vizzy/messages/en.json
frontend/vizzy/messages/pt.json

Added i18n translations for proposal status

feat: translations for proposal status

---

backend/vizzy-backend/src/proposal/proposal.controller.ts
frontend/vizzy/app/dashboard/proposals/[id]/proposal-details/page.tsx
frontend/vizzy/components/ui/overlay/image-preview-dialog.tsx
frontend/vizzy/lib/api/proposals/upload-proposal-images.ts

Also, a listing card is added to the proposals, making it easy for the user to access it.

feat: image preview on swap proposals

---

backend/vizzy-backend/src/listing/tests/unit/listing.service.spec.ts
frontend/vizzy/app/dashboard/layout/listings-page.tsx
frontend/vizzy/components/ui/navigation/pagination.tsx

Fixed a bug where the pagination options wouldn't appear on listings page

feat: pagination on listings page

---

backend/vizzy-backend/src/constants/cache/profile.cache-keys.ts
backend/vizzy-backend/src/dtos/listing/listing.dto.ts
backend/vizzy-backend/src/listing/tests/unit/listing.service.spec.ts
frontend/vizzy/app/listing/[id]/page.tsx
frontend/vizzy/components/profiles/profile-card.tsx
frontend/vizzy/messages/en.json
frontend/vizzy/messages/pt.json
frontend/vizzy/types/listing.ts
frontend/vizzy/types/profile.ts

Implementation of profile card in listing details

feat: profile card

---

backend/vizzy-backend/src/listing/helpers/listing-database.helper.ts
backend/vizzy-backend/src/listing/helpers/listing-image.helper.ts
backend/vizzy-backend/src/listing/listing.controller.ts
backend/vizzy-backend/src/listing/listing.service.ts
backend/vizzy-backend/src/listing/tests/integration/listing.database-helper.integration-spec.ts
frontend/vizzy/components/listings/create-listing-dialog.tsx

Refactor of the database helper that had some image related functions. Passed them to the image helper where they should be.

refactor: listing images

---

frontend/vizzy/app/dashboard/components/recent-sales.tsx
frontend/vizzy/app/dashboard/components/user-balance.tsx
frontend/vizzy/app/dashboard/layout/overview-page.tsx
frontend/vizzy/messages/en.json
frontend/vizzy/messages/pt.json

Implementation og the recent sales component

feat: recent sales component

---

backend/vizzy-backend/src/proposal/helpers/proposal-image.helper.ts

updated the sequence diagrams.

fix: sequence diagrams updated

---

frontend/vizzy/app/settings/components/profile-picture.tsx
frontend/vizzy/lib/api/profile/avatar.ts

Fixing the upload avatar functionality

fix: fix avatar upload

---

frontend/vizzy/app/landing/layout.tsx
frontend/vizzy/app/landing/page.tsx

Added landing page with YT video.

feat: landing page

---

frontend/vizzy/app/auth/login/components/user-login-form.tsx
frontend/vizzy/lib/actions/auth/login-action.ts

Fixed toasts not appearing on failed login.

fix: login toast errors

---

frontend/vizzy/components/proposals/rental-proposal-dialog.tsx

Fixed calendar going off the screen when making proposal.

fix: calendar going off screen

---

frontend/vizzy/components/layout/nav-bar/user-menu.tsx

Updated user menu to make it more simple and easy to use.

feat: update user menu

---

frontend/vizzy/app/dashboard/components/recent-sales.tsx
frontend/vizzy/app/dashboard/components/user-balance.tsx
frontend/vizzy/messages/en.json
frontend/vizzy/messages/pt.json
frontend/vizzy/package-lock.json
frontend/vizzy/package.json

fixing some details in dashboard

fix: small dashboard details

---

frontend/vizzy/app/dashboard/components/overview.tsx
frontend/vizzy/lib/api/overview/get-user-overview.ts
frontend/vizzy/lib/utils/supabase/client.ts
frontend/vizzy/lib/utils/supabase/server.ts
frontend/vizzy/lib/utils/token/get-server-user-action.ts

implementation of the graph of the dashboard

feat: dashboard graph

---

backend/vizzy-backend/src/dtos/listing/listing-basic.dto.ts
backend/vizzy-backend/src/listing/helpers/listing-database.helper.ts
backend/vizzy-backend/src/listing/tests/unit/listing.controller.spec.ts
backend/vizzy-backend/src/listing/tests/unit/listing.service.spec.ts
frontend/vizzy/app/dashboard/proposals/[id]/proposal-details/page.tsx
frontend/vizzy/components/listings/listing-card-normal.tsx
frontend/vizzy/components/profiles/profile-hover-card.tsx
frontend/vizzy/types/listing.ts

Added the owner details to the listing card

feat: owner details on listing card

---

frontend/vizzy/app/dashboard/dashboard-page-client.tsx
frontend/vizzy/messages/en.json
frontend/vizzy/messages/pt.json

fixed the json files conflicts

fix: dahsboard translation conflicts

---

frontend/vizzy/components/layout/nav-bar/user-menu.tsx
frontend/vizzy/messages/en.json
frontend/vizzy/messages/pt.json

feat: add favorites to user menu
